=== NHSDigital/nhs-notify-web-template-management/packages/event-schemas/schemas/TemplateDeleted/v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "maxLength": 1000,
      "description": "Unique ID for this event"
    },
    "time": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{3}Z$",
      "description": "Time the event was generated"
    },
    "type": {
      "type": "string",
      "const": "uk.nhs.notify.template-management.TemplateDeleted.v1"
    },
    "source": {
      "type": "string",
      "description": "Source of the event"
    },
    "specversion": {
      "type": "string",
      "const": "1.0",
      "description": "Version of the envelope event schema"
    },
    "datacontenttype": {
      "type": "string",
      "const": "application/json",
      "description": "Always application/json"
    },
    "subject": {
      "type": "string",
      "format": "uuid",
      "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
      "description": "Unique identifier for the item in the event data"
    },
    "dataschema": {
      "type": "string",
      "const": "https://notify.nhs.uk/events/schemas/TemplateDeleted/v1.json"
    },
    "dataschemaversion": {
      "type": "string",
      "pattern": "^1\\..*"
    },
    "plane": {
      "type": "string",
      "const": "control"
    },
    "data": {
      "$ref": "#/$defs/TemplateEventData"
    }
  },
  "required": [
    "id",
    "time",
    "type",
    "source",
    "specversion",
    "datacontenttype",
    "subject",
    "dataschema",
    "dataschemaversion",
    "plane",
    "data"
  ],
  "$defs": {
    "TemplateEventData": {
      "oneOf": [
        {
          "$ref": "#/$defs/EmailTemplateEventData"
        },
        {
          "$ref": "#/$defs/NhsAppTemplateEventData"
        },
        {
          "$ref": "#/$defs/LetterTemplateEventData"
        },
        {
          "$ref": "#/$defs/SmsTemplateEventData"
        }
      ]
    },
    "EmailTemplateEventData": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string",
          "description": "The client that owns the template"
        },
        "id": {
          "type": "string",
          "pattern": "^[\\dA-Fa-f]{8}(?:-[\\dA-Fa-f]{4}){3}-[\\dA-Fa-f]{12}$",
          "description": "Unique identifier for the template"
        },
        "clientId": {
          "description": "The client that owns the template",
          "type": "string",
          "maxLength": 1000
        },
        "createdAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was initially created"
        },
        "createdBy": {
          "description": "Unique identifier for the user that initially created the template",
          "type": "string",
          "maxLength": 1000
        },
        "name": {
          "type": "string",
          "maxLength": 1000,
          "description": "User-provided template name"
        },
        "updatedAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was most recently updated"
        },
        "updatedBy": {
          "description": "Unique identifier for the user that most recently updated the template",
          "type": "string",
          "maxLength": 1000
        },
        "message": {
          "type": "string",
          "maxLength": 100000,
          "description": "Message body for the email template"
        },
        "subject": {
          "type": "string",
          "maxLength": 1000,
          "description": "Subject field for the email template"
        },
        "templateType": {
          "type": "string",
          "const": "EMAIL",
          "description": "Template type"
        }
      },
      "required": [
        "owner",
        "id",
        "createdAt",
        "name",
        "updatedAt",
        "message",
        "subject",
        "templateType"
      ]
    },
    "NhsAppTemplateEventData": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string",
          "description": "The client that owns the template"
        },
        "id": {
          "type": "string",
          "pattern": "^[\\dA-Fa-f]{8}(?:-[\\dA-Fa-f]{4}){3}-[\\dA-Fa-f]{12}$",
          "description": "Unique identifier for the template"
        },
        "clientId": {
          "description": "The client that owns the template",
          "type": "string",
          "maxLength": 1000
        },
        "createdAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was initially created"
        },
        "createdBy": {
          "description": "Unique identifier for the user that initially created the template",
          "type": "string",
          "maxLength": 1000
        },
        "name": {
          "type": "string",
          "maxLength": 1000,
          "description": "User-provided template name"
        },
        "updatedAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was most recently updated"
        },
        "updatedBy": {
          "description": "Unique identifier for the user that most recently updated the template",
          "type": "string",
          "maxLength": 1000
        },
        "message": {
          "type": "string",
          "maxLength": 5000,
          "description": "Message body for the NHS App template"
        },
        "templateType": {
          "type": "string",
          "const": "NHS_APP",
          "description": "Template type"
        }
      },
      "required": [
        "owner",
        "id",
        "createdAt",
        "name",
        "updatedAt",
        "message",
        "templateType"
      ]
    },
    "LetterTemplateEventData": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string",
          "description": "The client that owns the template"
        },
        "id": {
          "type": "string",
          "pattern": "^[\\dA-Fa-f]{8}(?:-[\\dA-Fa-f]{4}){3}-[\\dA-Fa-f]{12}$",
          "description": "Unique identifier for the template"
        },
        "clientId": {
          "description": "The client that owns the template",
          "type": "string",
          "maxLength": 1000
        },
        "createdAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was initially created"
        },
        "createdBy": {
          "description": "Unique identifier for the user that initially created the template",
          "type": "string",
          "maxLength": 1000
        },
        "name": {
          "type": "string",
          "maxLength": 1000,
          "description": "User-provided template name"
        },
        "updatedAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was most recently updated"
        },
        "updatedBy": {
          "description": "Unique identifier for the user that most recently updated the template",
          "type": "string",
          "maxLength": 1000
        },
        "files": {
          "type": "object",
          "properties": {
            "proofs": {
              "type": "object",
              "propertyNames": {
                "type": "string"
              },
              "additionalProperties": {
                "type": "object",
                "properties": {
                  "supplier": {
                    "type": "string",
                    "maxLength": 1000
                  }
                },
                "required": [
                  "supplier"
                ]
              }
            }
          },
          "description": "Object containing information about proofs attached to the template"
        },
        "templateType": {
          "type": "string",
          "const": "LETTER",
          "description": "Template type"
        },
        "language": {
          "type": "string",
          "enum": [
            "ar",
            "bg",
            "bn",
            "de",
            "el",
            "en",
            "es",
            "fa",
            "fr",
            "gu",
            "hi",
            "hu",
            "it",
            "ku",
            "lt",
            "lv",
            "ne",
            "pa",
            "pl",
            "pt",
            "ro",
            "ru",
            "sk",
            "so",
            "sq",
            "ta",
            "tr",
            "ur",
            "zh"
          ],
          "description": "ISO 639 language code for the language the letter template is written in"
        },
        "letterType": {
          "type": "string",
          "enum": [
            "q1",
            "q4",
            "x0",
            "x1",
            "x3"
          ],
          "description": "Letter type - q1:Braille, q4:British Sign Language, x0:Standard, x1:Large Print, x3:Audio"
        },
        "personalisationParameters": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 1000
          },
          "description": "List of personalisation parameters used in the template"
        },
        "supplierReferences": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "required": [
        "owner",
        "id",
        "createdAt",
        "name",
        "updatedAt",
        "files",
        "templateType",
        "language",
        "letterType",
        "personalisationParameters"
      ]
    },
    "SmsTemplateEventData": {
      "type": "object",
      "properties": {
        "owner": {
          "type": "string",
          "description": "The client that owns the template"
        },
        "id": {
          "type": "string",
          "pattern": "^[\\dA-Fa-f]{8}(?:-[\\dA-Fa-f]{4}){3}-[\\dA-Fa-f]{12}$",
          "description": "Unique identifier for the template"
        },
        "clientId": {
          "description": "The client that owns the template",
          "type": "string",
          "maxLength": 1000
        },
        "createdAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was initially created"
        },
        "createdBy": {
          "description": "Unique identifier for the user that initially created the template",
          "type": "string",
          "maxLength": 1000
        },
        "name": {
          "type": "string",
          "maxLength": 1000,
          "description": "User-provided template name"
        },
        "updatedAt": {
          "type": "string",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$",
          "description": "Timestamp for when the template was most recently updated"
        },
        "updatedBy": {
          "description": "Unique identifier for the user that most recently updated the template",
          "type": "string",
          "maxLength": 1000
        },
        "message": {
          "type": "string",
          "maxLength": 918,
          "description": "Message body for the NHS App template"
        },
        "templateType": {
          "type": "string",
          "const": "SMS",
          "description": "Template type"
        }
      },
      "required": [
        "owner",
        "id",
        "createdAt",
        "name",
        "updatedAt",
        "message",
        "templateType"
      ]
    }
  },
  "$id": "https://notify.nhs.uk/events/schemas/TemplateDeleted/v1.json"
}

=== NHSDigital/nhs-notify-web-template-management/packages/event-schemas/examples/TemplateDeleted/v1/letter.json
{
  "data": {
    "clientId": "9c7b373b-4b8a-4b14-812b-f2759f6648fe",
    "createdAt": "2025-07-29T10:11:13.881Z",
    "createdBy": "INTERNAL_USER#fd70f0ac-4eb3-4159-bcfa-60a325cc1bf2",
    "files": {
      "docxTemplate": {
        "url": "s3://template-mgmt/nhs-notify-main-app/9c7b373b-4b8a-4b14-812b-f2759f6648fe/91be480d-c667-4741-957a-057b6475376/1641027600000.docx"
      }
    },
    "id": "91be480d-c667-4741-957a-057b64753762",
    "language": "en",
    "letterType": "x0",
    "letterVariantId": "letter-variant-id",
    "name": "Example Letter Template",
    "owner": "9c7b373b-4b8a-4b14-812b-f2759f6648fe",
    "personalisationParameters": [
      "test"
    ],
    "templateType": "LETTER",
    "updatedAt": "2025-07-29T11:15:22.776Z",
    "updatedBy": "INTERNAL_USER#fd70f0ac-4eb3-4159-bcfa-60a325cc1bf2"
  },
  "datacontenttype": "application/json",
  "dataschema": "https://notify.nhs.uk/events/schemas/TemplateDeleted/v1.json",
  "dataschemaversion": "1.2.1",
  "id": "20f471d0-367d-4914-bee3-2fa5322d67f1",
  "plane": "control",
  "source": "//notify.nhs.uk/app/nhs-notify-template-management-prod/main",
  "specversion": "1.0",
  "subject": "91be480d-c667-4741-957a-057b64753762",
  "time": "2025-07-29T11:15:22.776Z",
  "type": "uk.nhs.notify.template-management.TemplateDeleted.v1"
}

=== NHSDigital/nhs-notify-web-template-management/packages/event-schemas/examples/TemplateDeleted/v1/nhsapp.json
{
  "data": {
    "clientId": "d9159bb1-ac8c-467b-a990-b4e559ecdad3",
    "createdAt": "2025-07-29T10:04:32.738Z",
    "createdBy": "INTERNAL_USER#f2590ba5-6856-4207-b2dd-cd43821adf8b",
    "id": "3a58a370-75ab-4788-a75e-cd2572a68523",
    "message": "# Your GP Appointment\n\nDear ((firstName))\n\nYour appointment to visit the doctor is at **((appointmentTime))** on **((appointmentDate))**.\n\nIf you are unable to make your appointment, please click [this link](https://example.com) to cancel.\n\nThank you\n\n((surgeryName))\n",
    "name": "Example NHS App Template",
    "owner": "d9159bb1-ac8c-467b-a990-b4e559ecdad3",
    "templateStatus": "DELETED",
    "templateType": "NHS_APP",
    "updatedAt": "2025-07-29T11:16:24.519Z",
    "updatedBy": "INTERNAL_USER#f2590ba5-6856-4207-b2dd-cd43821adf8b"
  },
  "datacontenttype": "application/json",
  "dataschema": "https://notify.nhs.uk/events/schemas/TemplateDeleted/v1.json",
  "dataschemaversion": "1.2.1",
  "id": "c958dab9-1cb2-4fb8-9990-c48ba1dc5518",
  "plane": "control",
  "source": "//notify.nhs.uk/app/nhs-notify-template-management-prod/main",
  "specversion": "1.0",
  "subject": "3a58a370-75ab-4788-a75e-cd2572a68523",
  "time": "2025-07-29T11:16:24.519Z",
  "type": "uk.nhs.notify.template-management.TemplateDeleted.v1"
}

=== NHSDigital/nhs-notify-web-template-management/packages/event-schemas/examples/TemplateDeleted/v1/sms.json
{
  "data": {
    "clientId": "2faa156e-3d87-4e80-a022-31536b79daf4",
    "createdAt": "2025-07-29T09:45:42.472Z",
    "createdBy": "INTERNAL_USER#9228217c-b0d9-4368-81ec-64e0127d16f0",
    "id": "9779f827-0670-48b4-8e96-5cecf893468e",
    "message": "Dear ((firstName))\n\nYour appointment to visit the doctor is at ((appointmentTime)) on ((appointmentDate)).\n\nIf you are unable to make your appointment, please click this link  to cancel - https://example.com\n\nThank you\n\n((surgeryName))\n",
    "name": "Example SMS Template",
    "owner": "2faa156e-3d87-4e80-a022-31536b79daf4",
    "templateType": "SMS",
    "updatedAt": "2025-07-29T11:17:41.773Z",
    "updatedBy": "INTERNAL_USER#9228217c-b0d9-4368-81ec-64e0127d16f0"
  },
  "datacontenttype": "application/json",
  "dataschema": "https://notify.nhs.uk/events/schemas/TemplateDeleted/v1.json",
  "dataschemaversion": "1.2.1",
  "id": "58d46ca9-dae4-4500-9b9a-9e6547289e69",
  "plane": "control",
  "source": "//notify.nhs.uk/app/nhs-notify-template-management-prod/main",
  "specversion": "1.0",
  "subject": "9779f827-0670-48b4-8e96-5cecf893468e",
  "time": "2025-07-29T11:17:41.773Z",
  "type": "uk.nhs.notify.template-management.TemplateDeleted.v1"
}
