=== NHSDigital/nhs-notify-web-template-management/packages/event-schemas/schemas/ContactDetailVerificationRequested/v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "maxLength": 1000,
      "description": "Unique ID for this event"
    },
    "time": {
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{3}Z$",
      "description": "Time the event was generated"
    },
    "type": {
      "type": "string",
      "const": "uk.nhs.notify.template-management.ContactDetailVerificationRequested.v1"
    },
    "source": {
      "type": "string",
      "description": "Source of the event"
    },
    "specversion": {
      "type": "string",
      "const": "1.0",
      "description": "Version of the envelope event schema"
    },
    "datacontenttype": {
      "type": "string",
      "const": "application/json",
      "description": "Always application/json"
    },
    "subject": {
      "type": "string",
      "format": "uuid",
      "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
      "description": "Unique identifier for the item in the event data"
    },
    "dataschema": {
      "type": "string",
      "const": "https://notify.nhs.uk/events/schemas/ContactDetailVerificationRequested/v1.json"
    },
    "dataschemaversion": {
      "type": "string",
      "pattern": "^1\\..*"
    },
    "plane": {
      "type": "string",
      "const": "data"
    },
    "data": {
      "$ref": "#/$defs/ContactDetailVerificationRequestedEventData"
    }
  },
  "required": [
    "id",
    "time",
    "type",
    "source",
    "specversion",
    "datacontenttype",
    "subject",
    "dataschema",
    "dataschemaversion",
    "plane",
    "data"
  ],
  "$defs": {
    "ContactDetailVerificationRequestedEventData": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$",
          "description": "Unique identifier of the contact detail verification request"
        },
        "type": {
          "type": "string",
          "enum": [
            "EMAIL",
            "SMS"
          ],
          "description": "Type of contact detail that requires verification"
        },
        "value": {
          "type": "string",
          "description": "Contact detail that requires verification"
        },
        "otp": {
          "type": "string",
          "pattern": "^\\d{6}$",
          "description": "OTP to include in the contact detail verification message"
        }
      },
      "required": [
        "id",
        "type",
        "value",
        "otp"
      ]
    }
  },
  "$id": "https://notify.nhs.uk/events/schemas/ContactDetailVerificationRequested/v1.json"
}

=== NHSDigital/nhs-notify-web-template-management/packages/event-schemas/examples/ContactDetailVerificationRequested/v1/email.json
{
  "data": {
    "id": "120711be-ccd7-4104-a12a-b14ef668a815",
    "otp": "123456",
    "type": "EMAIL",
    "value": "user@example.com"
  },
  "datacontenttype": "application/json",
  "dataschema": "https://notify.nhs.uk/events/schemas/ContactDetailVerificationRequested/v1.json",
  "dataschemaversion": "1.0.0",
  "id": "8681f3a6-3553-492f-aab1-25c86fade338",
  "plane": "data",
  "source": "//notify.nhs.uk/app/nhs-notify-template-management-prod/main",
  "specversion": "1.0",
  "subject": "120711be-ccd7-4104-a12a-b14ef668a815",
  "time": "2026-04-27T10:30:00.000Z",
  "type": "uk.nhs.notify.template-management.ContactDetailVerificationRequested.v1"
}

=== NHSDigital/nhs-notify-web-template-management/packages/event-schemas/examples/ContactDetailVerificationRequested/v1/sms.json
{
  "data": {
    "id": "41e2303d-976e-4ad2-a2d6-442a1a26934e",
    "otp": "654321",
    "type": "SMS",
    "value": "+447890123456"
  },
  "datacontenttype": "application/json",
  "dataschema": "https://notify.nhs.uk/events/schemas/ContactDetailVerificationRequested/v1.json",
  "dataschemaversion": "1.0.0",
  "id": "ea03d606-3d6c-4720-bda4-5375e146eff2",
  "plane": "data",
  "source": "//notify.nhs.uk/app/nhs-notify-template-management-prod/main",
  "specversion": "1.0",
  "subject": "41e2303d-976e-4ad2-a2d6-442a1a26934e",
  "time": "2026-04-27T10:30:00.000Z",
  "type": "uk.nhs.notify.template-management.ContactDetailVerificationRequested.v1"
}
